.TH MySecureShell 8 "03/05/2006" mss-utils "MySecureShell's manual"
.SH NAME
MySecureShell - Command
.SH SYNOPSYS
.TP
\fB/bin/MySecureShell\fP [verbose] [options]
.SH DESCRIPTION
.SS Verbose
.TP
-v: show more informations for option \fB--configtest\fP
.SS Options
.TP
--configtest: test the config file and show errors
.TP
--help: show help
.TP
--version: show version of MySecureShell
.SH EXAMPLES
.TP
/bin/MySecureShell --help
Show help of MySecureShell 
.SH SEE ALSO
sftp-kill(8), sftp-who(8), sftp-state(8), sftp-admin(8) sftp-verif(8)
