.TH sftp-verif 8 "03/05/2006" mss-utils "sftp-verif Manual for MySecureShell"
.SH NAME
sftp-verif - MySecureShell Command
.SH DESCRIPTION
Very useful to verify and correct problems on a MySecureShell server.
.SH EXAMPLES
.TP
\fBsftp-verif\fP
Verify and correct problems on the server 
.SH SEE ALSO
MySecureShell(8), sftp-who(8), sftp-state(8), sftp-admin(8) sftp-verif(8)
