.TH sftp-kill 8 "03/05/2006" mss-utils "sftp-kill Manual for MySecureShell"
.SH NAME
sftp-kill - MySecureShell Command
.SH SYNOPSYS
\fBsftp-kill\fP [user] ...
.SH DESCRIPTION
Disconnect users to the server.
.SH EXAMPLES
.TP
\fBsftp-kill user1 user2\fP
Disconnect user1 and user2
.TP
\fBsftp-kill all\fP
Disconnect every users.
.SH SEE ALSO
MySecureShell(8), sftp-who(8), sftp-state(8), sftp-admin(8) sftp-verif(8)
