.TH sftp-user 8 "16/10/2007" mss-utils "sftp-user Manual for MySecureShell"
.SH NAME
sftp-user - MySecureShell Command
.SH SYNOPSYS
\fBsftp-user\fP
.SH DESCRIPTION
Create MySecureShell users easily (requiered for MySecureSHell Graphical Tool).
.SH SEE ALSO
MySecureShell(8), sftp-user(8), sftp-state(8), sftp-admin(8) sftp-verif(8)
