.TH MySecureShell 8 "03/05/2006" mss-utils "Manuel de MySecureShell"
.SH NOM
MySecureShell - Commande
.SH SYNOPSYS
.TP
\fB/bin/MySecureShell\fP [verbose] [options]
.SH DESCRIPTION
.SS Verbose
.TP
-v: affiche plus d'informations pour l'option option \fB--configtest\fP
.SS Options
.TP
--configtest: test le fichier de configuration et montre les erreurs
.TP
--help: affiche l'aide
.TP
--version: affiche la version de MySecureShell
.SH EXEMPLES
.TP
/bin/MySecureShell --help
Affiche l'aide de MySecureShell 
.SH VOIR AUSSI
sftp-kill(8), sftp-who(8), sftp-state(8), sftp-admin(8) sftp-verif(8)
