.TH sftp-kill 8 "03/05/2006" mss-utils "Manuel de sftp-kill pour MySecureShell"
.SH NOM
sftp-kill - Commande MySecureShell
.SH SYNOPSYS
\fBsftp-kill\fP [utilisateur] ...
.SH DESCRIPTION
Deconnecte des clients du serveur.
.SH EXEMPLES
.TP
\fBsftp-kill user1 user2\fP
Deconnecte les clients user1 et user2.
.TP
\fBsftp-kill all\fP
Deconnecte tout les clients.
.SH VOIR AUSSI
MySecureShell(8), sftp-who(8), sftp-state(8), sftp-admin(8) sftp-verif(8)
