.TH sftp-verif 8 "03/05/2006" mss-utils "Manuel de sftp-verif pour MySecureShell"
.SH NOM
sftp-verif - Commande MySecureShell
.SH DESCRIPTION
Tres utile pour verifier et corriger d'eventuels problemes sur un serveur MySecureShell.
.SH EXEMPLES
.TP
\fBsftp-verif\fP
Verifie et corrige d'eventuels problemes sur le serveur.
.SH VOIR AUSSI
MySecureShell(8), sftp-who(8), sftp-state(8), sftp-admin(8) sftp-verif(8)
