.TH sftp-admin 8 "03/05/2006" mss-utils "Manuel de sftp-admin pour MySecureShell"
.SH NOM
sftp-admin - Commande MySecureShell
.SH SYNOPSYS
\fBsftp-admin\fP [options ssh] user@hostname
.SH DESCRIPTION
Permet d'administrer a distance un serveur MySecureShell.
.SS OPTIONS
.TP
options ssh : passe des options au serveur ssh
.TP
user@hostname : user est votre administrateur et hostname est l'adresse de votre serveur
.SH EXEMPLES
.TP
\fBsftp-admin [ssh options] MSS@hostname\fP
MSS administre le serveur hostname avec le port 22.
.TP
\fBsftp-admin [ssh options] MSS@hostname:2006\fP
MSS administre le serveur hostname avec le port 2006.
.SH VOIR AUSSI
MySecureShell(8), sftp-who(8), sftp-state(8), sftp-kill(8) sftp-verif(8)
