.TH sftp-user 8 "16/10/2007" mss-utils "Manuel de sftp-user pour MySecureShell"
.SH NOM
sftp-user - Commande MySecureShell
.SH SYNOPSYS
\fBsftp-user\fP
.SH DESCRIPTION
Permet de creer simplement des utilisateurs (requis pour la version graphique).
.SH VOIR AUSSI
MySecureShell(8), sftp-user(8), sftp-state(8), sftp-admin(8) sftp-verif(8)
