#!/bin/sh
# postinst script for mysecureshell
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Validating Shell
add-shell /usr/bin/mysecureshell

# Reassign rights
cd /usr/bin
chmod 755 sftp-who sftp-verif sftp-user
chmod 700 sftp-state sftp-kill sftp-admin
# If sticky bit exist, do not override it
test -u mysecureshell || chmod 755 mysecureshell

#DEBHELPER#

exit 0

